0.6.0 saved synchronized
Cretezy/redux_persist pull request #26
Opened 2018-10-02 07:39 UTC by nullp01nt3r

Addressing issue #25 .

2018-10-02 07:40 UTC, nullp01nt3r commented
Relevant commit is obviously 9b32506

2018-10-02 14:37 UTC, Cretezy commented
Nice work. I would actually move this up to be in `redux_persist`, so it applies to both web and Flutter.

Also you should [global ignore](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c) all `*.iml` and `.idea` files.

2018-10-02 14:39 UTC, Cretezy requested changes

2018-10-02 14:39 UTC, Cretezy commented on packages/redux_persist_flutter/redux_persist_flutter.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Ignore globally (as said in thread comment) and `git rm --cached packages/redux_persist_flutter/redux_persist_flutter.iml`

2018-10-02 14:39 UTC, Cretezy commented on packages/redux_persist_flutter/pubspec.yaml
> +  synchronized: "^1.5.3"
Move to `redux_persist` package.

2018-10-02 14:39 UTC, Cretezy commented on packages/redux_persist_flutter/pubspec.yaml
> +version: 0.6.0-save-sync-2-SNAPSHOT
Bump it to `0.6.0` please

2018-10-02 14:39 UTC, Cretezy commented on packages/redux_persist_flutter/pubspec.yaml
> +  sdk: ">=2.0.0-dev <3.0.0"
This is odd. I remember doing this change. I might have an unpushed commit on my desktop

2018-11-06 05:09 UTC, Cretezy commented
This was merged in 0.8.0-rc.0

2018-11-06 05:09 UTC, closed without merging